name: Chained Jobs
on:
 push:

jobs:
  job_1:
    runs-on: self-hosted
    steps:
      - run: "echo Job: ${{ github.job }}"
  job_2:
    runs-on: self-hosted
    needs: job_1
    steps:
      - run: "echo Job: ${{ github.job }}"
  job_3:
    runs-on: self-hosted
    needs: job_1
    steps:
      - run: "echo Job: ${{ github.job }}"
  job_4:
    runs-on: self-hosted
    needs: [job_2, job_3]
    steps:
      - run: "echo Job: ${{ github.job }}"
